# Generated by Django 4.0.3 on 2022-04-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('moderated', 'Moderated'), ('new', 'New')], default='new', max_length=50, verbose_name='Status')),
                ('added_date', models.DateTimeField(auto_now=True, verbose_name='Date of addition')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
            },
        ),
    ]
